name: Security Scanning

on:
  push:
    paths:
      - 'terraform/**'
      - 'tasky-main/**'
      - '.github/workflows/security-scan.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - 'tasky-main/**'

jobs:
  tfsec:
    name: TFSec Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run TFSec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working-directory: terraform

  trivy:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'tasky-main'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif' 