name: Security Scan

on:
  push:
    paths:
      - 'terraform/**'
      - 'tasky-main/**'
  pull_request:
    paths:
      - 'terraform/**'
      - 'tasky-main/**'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working-directory: terraform 