name: Security Scanning

on:
  push:
    branches: [ main ]
    paths: [ 'terraform/**', 'tasky-main/Dockerfile', 'tasky-main/**/*.go' ]
  pull_request:
    branches: [ main ]
    paths: [ 'terraform/**', 'tasky-main/Dockerfile', 'tasky-main/**/*.go' ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM

jobs:
  tfsec:
    name: TFSec Scan
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'terraform/') || contains(github.event.head_commit.added, 'terraform/')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run TFSec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working_directory: terraform
        format: sarif
        out: tfsec.sarif

    - name: Upload TFSec scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: terraform/tfsec.sarif

  checkov:
    name: Checkov Scan
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'terraform/') || contains(github.event.head_commit.added, 'terraform/')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform
        framework: terraform
        output_format: sarif
        output_file_path: checkov.sarif

    - name: Upload Checkov scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: checkov.sarif

  gosec:
    name: Go Security Scan
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, '*.go') || contains(github.event.head_commit.added, '*.go')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Gosec Security Scanner
      working-directory: tasky-main
      uses: securecodewarrior/github-action-gosec@master
      with:
        args: '-fmt sarif -out gosec.sarif ./...'

    - name: Upload Gosec scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: tasky-main/gosec.sarif 